---
# tasks file for packages

- name: Vérification de la présence du dossier policy-rc.d
  stat:
    path: /usr/sbin/policy-rc.d
  register: packages_result_policy
  when: ansible_distribution == 'Debian'

- name: Création du dossier de politique
  file:
    path: /usr/sbin/policy-rc.d
    state: touch
    mode: 0755
  when: 
    - packages_result_policy.stat.exists == false
    - ansible_distribution == 'Debian'

- name: Politique de blocage du starting des processes à l'installation
  lineinfile:
    path: /usr/sbin/policy-rc.d
    line: |
      #!/bin/sh
      echo "All runlevel operations denied by policy" >&2
      exit 101
  when: 
    - packages_result_policy.stat.exists == false
    - ansible_distribution == 'Debian'

- name: Preparation de la mise à jour de apt
  apt: 
    name: 'apt-transport-https'
    state: installed
  when: ansible_distribution == 'Debian'

- name: Mise à jour du cache pour apt
  apt:
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Installation des packages
  apt: 
    name: '{{ item }}'
    state: installed
  with_items: '{{ packages_list }}'
  when: ansible_distribution == 'Debian'

- name: Redhat - Installation des packages
  yum: 
    name: '{{ item }}'
    state: installed
  with_items: '{{ packages_list }}'
  when: ansible_distribution == 'Redhat'

- name: Ajout du repository pour installer docker
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    state: present
  ignore_errors: yes
  failed_when: false
  when: ansible_distribution == 'Debian'

- name: Ajout de la clé gpg pour docker
  apt_key:
    keyserver: pgpkeys.mit.edu
    id: F76221572C52609D
  ignore_errors: yes
  failed_when: false
  when: ansible_distribution == 'Debian'

######################################## Redhat #########################################
# - name: Add repository
#   yum_repository:
#     name: epel
#     description: EPEL YUM repo
#     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#   when: ansible_distribution == 'Redhat'

...